### ISSUE TITLE
Smooth Speed Control for Height Adjustment

### ISSUE THREAD

**Issue by dosoft** [rhyst/linak-controller#84]
Is it possible to implement a feature that allows for smooth speed regulation during height adjustments?

The proposed idea revolves around gradually slowing down the table's movement as it approaches the desired height. This adjustment aims to prevent abrupt stop, ensuring a more seamless operation.

Thank you for considering this enhancement!

**Comment by rhyst** [comment]
As far as I know there is no way to control the speed of the desk. In the movement commands you either provide an "up" or "down" command or provide a target height. 

Do you get different speed using the physical buttons/official app compared to using linak controller?
