### ISSUE TITLE
Query desk height without server mode?

### ISSUE THREAD

**Issue by iamchanghyunpark** [rhyst/linak-controller#93]
Hello, I'm trying to use a HomeKit shortcut button to create a shortcut that toggles between two heights.
But first I need to know the current height of the desk to do this.

I could have my desktop computer serve as the server and use the `--forward` command to read out the height.
But I was also wondering if we could use the `linak-controller` command (without a server) to quickly query the desk height.
A simple output similar to the `--forward` command would be what I'm looking for.

(I understand that this type of query might have a longer latency as the command would need to establish a connection with the desk every time (which has some latency)

Is there a query such as `linak-controller --height` that might query and print the current height of the desk?

**Comment by rhyst** [comment]
You get the height back if you just run `linak-controller` (no server needed)
